---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": ">=2.5.1"
license_file: LICENSE
name: yang
namespace: ansible
description: Ansible Network Collection to support yang.
readme: README.md
repository: https://github.com/ansible-collections/ansible.yang
issues: https://github.com/ansible-collections/ansible.yang/issues
tags: [networking, security, netconf]
version: 1.0.1
