---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  ansible.netcommon: '>=6.0.0'
description: Ansible yang collection for yang based operation
license_file: LICENSE
name: yang
namespace: ansible
readme: README.md
repository: https://github.com/ansible-collections/ansible.yang
tags: [networking, security, cloud, network_cli, netconf, httpapi, grpc]
version: '3.0.0'
