---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": ">=2.5.1"
license_file: LICENSE
name: yang
namespace: ansible
readme: README.md
repository: https://github.com/ansible-collections/ansible.yang
tags: [networking, security, cloud, network_cli, netconf, httpapi, grpc]
version: null
