---
name: Test collection

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  ansible-lint:
    uses: ansible-network/github_actions/.github/workflows/ansible-lint.yml@main
  changelog:
    uses: ansible-network/github_actions/.github/workflows/changelog.yml@main
    if: github.event_name != 'schedule'
  sanity:
    uses: ansible-network/github_actions/.github/workflows/sanity.yml@main
  all_green:
    if: ${{ always() && (github.event_name != 'schedule') }}
    needs:
      - ansible-lint
      - changelog
      - sanity
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert set([
          '${{ needs.ansible-lint.result }}',
          '${{ needs.changelog.result }}',
          '${{ needs.sanity.result }}',
          ]) == {'success'}"